---
########################################
# Set custom variables here.
########################################

# SSH user
#ansible_user: vagrant
#ansible_ssh_pass: vagrant

# Network
#private_iface: enp0s8
#public_iface: enp0s3

# Timezone
common_timezone: "Europe/Paris"
